Publish packages to npmjs
OasisDEX/summerfi-monorepo pull request #155
Opened 2024-04-04 14:23 UTC by cristidas

- Publish `sdk/sdk-common` and 'sdk/sdk-client' as packages to npmjs
- Trigger automatically on version changes to `main` branch or manually for code on `dev` and `main` branches`

2024-04-04 22:58 UTC, nickkounz approved these changes

2024-04-05 09:43 UTC, piotrwitek requested changes

2024-04-05 09:43 UTC, piotrwitek commented on sdk/sdk-client/package.json
> -  "name": "@summerfi/sdk-client",
revert please, this will not be publised

2024-04-05 09:43 UTC, piotrwitek commented on sdk/sdk-common/package.json
> -  "name": "@summerfi/sdk-common",
revert please

2024-04-05 09:43 UTC, piotrwitek commented on .github/workflows/publish-client-package.yaml
> +      working-directory: sdk/sdk-client/bundle
pnpm i at the monorepo root level and also pnpm build

2024-04-05 09:43 UTC, piotrwitek commented on .github/workflows/publish-client-package.yaml
> +      working-directory: sdk/sdk-client/bundle
change to sdk/sdk-client

2024-04-05 09:43 UTC, piotrwitek commented on .github/workflows/publish-client-package.yaml
> +      run: pnpm bundle:npm
change to pnpm publish:npm

2024-04-05 09:43 UTC, piotrwitek commented on .github/workflows/publish-common-package.yaml
> +        NPM_ACCESS_TOKEN: ${{ inputs.npm_access_token }}
same changes as in publish-client-package.yaml

2024-04-05 12:15 UTC, piotrwitek approved these changes
looks good thanks

2024-04-05 12:17 UTC, merged