fix: User/UserClient and Fleet/Fleet client classes
OasisDEX/summerfi-monorepo pull request #421
Opened 2024-07-09 15:18 UTC by robercano

- Fixes the implementation of UserClient and FleetClient by having proper User and Fleet base classes
- Fleet has been renamed to EarnProtocolFleet
- Fixed E2E tests and tested Earn Protocol against the endpoint to make sure the changes are working
- Minor fixes
- Several changes are due to import order fixing by VSCode plugin

2024-07-09 18:13 UTC, piotrwitek requested changes
looks great I just just spotted few improvements to consider

2024-07-10 10:40 UTC, robercano commented on sdk/sdk-e2e/tests/earnProtocol.test.ts
> +  SDKApiUrl: 'https://72dytt1e93.execute-api.us-east-1.amazonaws.com/api/sdk',
Yes, although we need to talk about how to properly do the E2E tests first (like having a proper DevNet for them, and an SDK endpoint so they can be run. For now E2E tests are skipped altogether during `cicheck`

2024-07-10 10:41 UTC, robercano commented on sdk/sdk-client/src/implementation/EarnProtocolManagerClient.ts
>        ...params,
So the benefit of doing that is that any new parameters are automatically handled. The con is that you may effectively be passing more parameters. Not sure what is best to have

2024-07-11 09:22 UTC, robercano commented on sdk/sdk-client/src/implementation/EarnProtocolManagerClient.ts
>        ...params,
Agreed to destructure it in cases where we are merging different types of parameters like this one, and not to destructure it when `params` can be passed untouched

2024-07-11 09:22 UTC, robercano commented on sdk/sdk-e2e/tests/earnProtocol.test.ts
> +  SDKApiUrl: 'https://72dytt1e93.execute-api.us-east-1.amazonaws.com/api/sdk',
Agreed to have a discussion offline to implement this at a later time

2024-07-11 09:37 UTC, piotrwitek approved these changes

2024-07-11 09:37 UTC, merged